### ISSUE TITLE
boot w/ the dev-dist build

### ISSUE THREAD

**Issue by ylxxwx** [tinkerbell/hook#114] opened 2022-04-18 20:01 UTC
I build w/ dev-dist. The boot stuck.

## Expected Behaviour
Expect boot successful and see shell.

## Current Behaviour
Stuck in boot. Pls see the attached picture. it stuck after init

## Steps to Reproduce (for bugs)

1. build dev-dist
2. put the vmlinuxz and initramfs into current dir
3. boot client
4. client stuck
5. 
![Screenshot from 2022-04-18 15-58-38](https://user-images.githubusercontent.com/42388346/163869133-305c9322-33cc-45ce-b1c0-b0f717acbbb5.png)

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by double-p** [comment] 2022-04-27 08:25
Same issue here; running on macOS with vagrant-virtualbox.

I tracked this down in the tink-docker container where you can find this:
````
{"level":"info","ts":1651047221.0680003,"caller":"cmd/root.go:45"
*msg": "starting","service":"github.com/tinkerbell/tink","version": "2h87714"}
Error: worker Finished with error: failed to get workflow context: rpc error:
code = Unavailable desc = connection error:
desc = "transport: authentication handshake failed: x509: certificate signed
by unknown authority"
Usage:
  tink-worker [flags]
 <more usage() stripped>
````
I tried several permutations in /etc/docker/certs.d - to no avail. Debugging certs via calling that directly, so from
the hook getty shell:
`ctr -n services.linuxkit task exec -t --exec-id testit docker sh`
`docker login ...`
`docker run 192.168.56.4/tink-worker -i 1 -r 192.168.56.4 -u admin -p Admin1234
 --tinkerbell-grpc-authority 192.168.56.4:42113`

Also tried by storing the presented server cert on 192.168.56.4:443 in /etc/docker/certs.d under 192.168.56.4 and 192.168.56.4:443 to no avail.

**Comment by double-p** [comment] 2022-04-27 09:35
ok, this is gRPC and has nothing along docker certs. the `ca.pem` needs to be added to the tink-worker container FS (/etc/ssl/certs/ca-certificates.crt or extra /etc/ssl/certs/myveryca.pem -- both work).
Fiddling on how to build such an image....

**Comment by double-p** [comment] 2022-04-27 12:13
fallout from https://github.com/tinkerbell/tink/pull/584

**Comment by nshalman** [comment] 2022-05-03 15:36
> fallout from [tinkerbell/tink#584](https://github.com/tinkerbell/tink/pull/584)

Caused by that PR, or resolved by it?

**Comment by double-p** [comment] 2022-05-03 15:42
Caused.. I was able to rollback the image hashes used in the sandbox and there it works. More bits of diagnose and blister help in this issue https://github.com/tinkerbell/sandbox/issues/133

**Comment by jacobweinstock** [comment] 2023-01-28 22:05
Hey @ylxxwx, quite a bit of change to Hook since you reported this. Mind trying with the latest commit?

**Comment by jacobweinstock** [comment] 2023-08-25 22:21
Please reopen if the issue still exists in the latest hook, thanks.

**Closed by jacobweinstock** 2023-08-25 22:21 UTC
Labels: priority/important-soon, kind/regression
